[project]
name = "ainews-podcast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "podcastfy>=0.4.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]

